### ISSUE TITLE
Sync repo from fiveai

### ISSUE THREAD

**Issue by ahmet2mir** [ubccr/goipa#4]
Hello,

[fiveai repo](https://github.com/fiveai/goipa) has more features like group management, any chances to you get it merge ? @fiveai @tustvold what do you think ?

I added features from fiveai fork but it will be more simple if everyone merge contribs in one place ?

**Comment by tustvold** [comment]
Hi @ahmet2mir I no longer work at FiveAI nor with FreeIPA, so I can't attest to whether the fork still works correctly, but I'm happy for the changes to be incorporated here if the maintainer is.

I feel I should add the implementation of some aspects of that fork are pretty nasty due to deficiencies in the FreeIPA API. It was a quick and dirty thing to get a [terraform provider](https://github.com/fiveai/terraform-provider-freeipa) working.

**Comment by aebruno** [comment]
Hello, I still actively maintain this and would be happy to accept any PRs. Thanks!

**Comment by ahmet2mir** [comment]
Great! I will prepare a PR, thank you for your work.

And yes it works well and the terraform provider too.


Le mer. 25 mars 2020 à 13:54, Andrew E. Bruno <notifications@github.com> a
écrit :
